AllCops:
  Includes:
    - Rakefile
    - lib/**
  Excludes:
    - bin/**
    - manifests/**
    - spec/fixtures/**

LineLength:
  Max: 120

HashSyntax:
  EnforcedStyle: hash_rockets

Lambda:
  Enabled: false
