AllCops:
  Include:
    - Rakefile
    - lib/**/*
  Exclude:
    - bin/**/*
    - manifests/**/*
    - spec/fixtures/**/*

LineLength:
  Max: 120

HashSyntax:
  EnforcedStyle: hash_rockets

Lambda:
  Enabled: false

NilComparison:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
