---
language: ruby
before_install: rm Gemfile.lock || true
rvm:
  - 2.0.0
script: bundle exec rake spec
env:
  matrix:
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 4.0.0"
matrix:
  include:
    - rvm: 2.4.0
      env: PUPPET_VERSION="~> 4.0.0"
    - rvm: 2.1.0
      env: PUPPET_VERSION="~> 4.0.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.3.0"
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0"
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 4.0.0"
